2022-02-25 19:00:01,465 CRITICAL server_log_config.py Критическая ошибка
2022-02-25 19:00:01,465 ERROR server_log_config.py Ошибка
2022-02-25 19:00:01,465 DEBUG server_log_config.py Отладочная информация
2022-02-25 19:00:01,465 INFO server_log_config.py Информационное сообщение
2022-02-25 20:24:38,036 INFO server.py Установлено соединение с ('127.0.0.1', 51357)
2022-02-25 20:24:38,036 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645795478.0207224, 'user': {'account_name': 'Guest'}}
2022-02-25 20:24:38,036 INFO server.py Сформирован ответ клиенту {'response': 200}
2022-02-25 20:24:38,036 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51357) закрывается
2022-02-25 20:26:47,283 INFO server.py Установлено соединение с ('127.0.0.1', 51362)
2022-02-25 20:26:47,283 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645795607.2839317, 'user': {'account_name': 'Guest'}}
2022-02-25 20:26:47,283 INFO server.py Сформирован ответ клиенту {'response': 200}
2022-02-25 20:26:47,283 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51362) закрывается
2022-02-25 20:45:46,408 ERROR server.py После параметра "-p" не указан порт. Сервер завершается
2022-02-25 20:45:57,582 INFO server.py Сервер в работе, порт: 7777
2022-02-25 20:45:57,582 ERROR server.py После параметра "-a" не указан адрес. Сервер завершается
2022-02-25 20:46:39,657 CRITICAL server.py Попытка запуска сервера с недопустимым портом: 999. Сервер завершается
2022-02-25 20:46:49,648 INFO server.py Сервер в работе, порт: 9999
2022-02-25 20:46:49,649 INFO server.py Сервер в работе, слушает всех
2022-02-25 20:47:07,109 INFO server.py Установлено соединение с ('127.0.0.1', 51430)
2022-02-25 20:47:07,109 DEBUG server.py Получено сообщение {'action': 'presence', 'time': 1645796827.1098692, 'user': {'account_name': 'Guest'}}
2022-02-25 20:47:07,111 INFO server.py Сформирован ответ клиенту {'response': 200}
2022-02-25 20:47:07,111 DEBUG server.py Соединение с клиентом ('127.0.0.1', 51430) закрывается
